.\" $XFree86: xc/programs/Xserver/hw/xfree86/reconfig/reconfig.man,v 3.8 1998/04/05 02:28:42 dawes Exp $
.TH reconfig 1 __vendorversion__
.SH NAME
reconfig \- convert old Xconfig to new __xconfigfile__
.SH SYNOPSIS
.B reconfig
<
.I Xconfig
>
.I __xconfigfile__
.SH DESCRIPTION
The \fIreconfig\fP program converts the Xconfig file format used
by other X servers into the __xconfigfile__ format currently
used.  The __xconfigfile__ format contains more information than the Xconfig
format, so manual editing is required after converting.
.SH "SEE ALSO"
__xservername__(__appmansuffix__), __xconfigfile__(__filemansuffix__), xorgconfig(__appmansuffix__)
.SH AUTHOR
Gertjan Akkerman.
.SH BUGS
Comment lines are stripped out when converting.
.\" $TOG: reconfig.man /main/9 1997/07/19 10:50:33 kaleb $
